asv_files_demo/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url('filerpc/', include('asv_files.dj.urls', namespace='asv_files')),
)
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
           'document_root': settings.MEDIA_ROOT,
        }),
    )
urlpatterns += patterns('',
    url('', include('demo.urls', namespace='demo')),
)

demo/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url
from views import *

urlpatterns = patterns('',
    url(r'ok/$', OK.as_view(), name='success'),
    url(r'^$', Demo1.as_view(), name='form1'),
)

demo/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import smart_unicode
from django.utils.timezone import *

#---------------------------------------------------------------
#---------------------------------------------------------------
class Zakaz(models.Model):
    active = models.BooleanField(default=True)
    title  = models.CharField(max_length=128, blank=True)
    de     = models.DateTimeField(auto_now_add=True)
    lm     = models.DateTimeField(auto_now=True)
    #----------
    def __unicode__(self):
        d = make_naive(self.de,get_current_timezone()).strftime('%Y-%m-%d %H:%M:%S')
        return smart_unicode('({date})  {title}'.format(
            title=self.title or '-unnamed-',
            date=d
        ))
    class Meta:
        ordering = ('de',)
        verbose_name='заказ'
        verbose_name_plural='заказы'
#-------------------------------------------------------------------
#-------------------------------------------------------------------

demo/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponseRedirect
from django.views.generic.edit import FormView
from django.views.generic.base import TemplateView
from django import forms
from asv_files.dj.fields import *
from asv_utils.dj import reverse_lazy
from demo.models import Zakaz

#----------------------------------------------------------------
class Demo1Form(forms.Form):
    subject = forms.CharField(max_length=50)
    files = CTfilesFormField()
    files2 = CTfilesFormField()
#----------------------------------------------------------------
class Demo1(FormView):
    template_name = 'demo1.html'
    form_class    = Demo1Form
    success_url   = reverse_lazy('demo:success')

    def form_valid(self, form):
        ooo = Zakaz(title=form.cleaned_data['subject'])
        ooo.save()    # need for attaching files
        files = form.cleaned_data['files']
        for i in files.get_files():
            #print('*** file {frn} saved as {fn} ({fp}) and have ID:{id}'.format(
            #    frn = i.get_realname(),
            #    fn = i.get_filename(),
            #    fp = i.get_filepath(),
            #    id = i.get_fileid(),
            #))
            i.attach_to(ooo) # save and attach files through ContentTypes to ooo.
                             # ooo MUST be created and saved before it.
            #i.delete() # remove file from database and storage. not need if we call files.delete()
        files.delete() # remove session and her files from database and storage
        files2 = form.cleaned_data['files2']
        for i in files2.get_files():
            i.attach_to(ooo)
        files2.delete()
        #
        return HttpResponseRedirect(self.get_success_url())
#----------------------------------------------------------------
class OK(TemplateView):
    template_name = 'ok.html'

demo/templates/demo1.html
{% extends "base.html" %}

{% block add_to_head %}
    {{form.media}}
{% endblock %}

{% block wp %}
    <hr>
    <form method="POST" action="{% url 'demo:form1' %}">{% csrf_token %}
        <table>{{ form.as_table }}</table>
        <BR><BR>
        <input type="submit"> <input type="reset">
    </form>
{% endblock %}

demo/templates/ok.html
{% extends "base.html" %}

{% block add_to_head %}
    {{FORM.media}}
{% endblock %}

{% block wp %}
    <p>Form and files saved succefully...</p>
    <p><a href="{% url 'demo:form1' %}">continue...</a></p>
{% endblock %}

templates/base.html
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link href="/static/css/style.css" media="all" rel="stylesheet" type="text/css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js" type="text/javascript"></script>
    {% block add_to_head %}{% endblock %}
</head>
<body{%if BODYCLASS %} class="{{BODYCLASS}}"{% endif %}>
    <div id="wp">
        {% block wp %}{% endblock %}
    </div>
</body>
</html>